version: '3.8'

services:
  backend_api:
    build: backend_azoth/
    ports: 
      - 8001:8001
    networks:
      - deploy_network
    container_name: backend_api

  frontend_app:
    build: frontend_azoth/
    depends_on:
      - backend_api
    ports: 
        - 8501:8501
    networks:
      - deploy_network
    container_name: frontend_app

networks:
  deploy_network:
    driver: bridge